<a href="https://colab.research.google.com/github/leejunghyunA/deeplearning-_study/blob/main/mininet_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 작은 단위의 layer 먼저 만들기
import torch
from torch import nn

In [ ]:
x = torch.randn(100,3)
layer = nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[-0.2932,  0.0778,  0.0877],
        [ 0.2307,  0.4677, -0.0518],
        [ 0.3353, -0.3334,  0.3464],
        [-0.2683, -0.2720, -0.4440],
        [-0.3229,  0.0467,  0.1786]], requires_grad=True)
Parameter containing:
tensor([ 0.3515, -0.4629, -0.5352,  0.1648,  0.2828], requires_grad=True)


In [ ]:
x = torch.randn(2,5)
layer = nn.ReLU() # 양수면 그대로, 음수면 0을 출력하는 함수
print(layer(x))

tensor([[0.1046, 0.0000, 0.1250, 1.2932, 1.3944],
        [0.7684, 0.0972, 1.3836, 0.6648, 0.6989]])


In [ ]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3)# p는 죽일 확률
print(drop(x))

tensor([[ 1.3721,  0.0000,  0.7538,  0.8716,  2.7066,  0.0000, -0.8607],
        [ 0.0000,  1.0584,  1.7092, -2.3161,  0.2332, -0.7191,  2.1536],
        [-0.0000, -0.3797, -0.0000,  0.0000,  2.7992,  1.7068, -0.9299]])


In [ ]:
# train과 evaluation 확인
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))
                                      
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode (0이 1개도 없음_dropout은 test와 train때랑 다름 : 이유? dropout전 값에 0.7을 곱해줌줌)

tensor([[-0.7414, -0.0000,  0.8323, -0.0000, -0.2257,  1.2635, -1.4077],
        [-0.6035,  0.0000,  1.2028,  0.0000, -0.0631, -0.2631, -2.0991],
        [ 1.4479, -2.5034, -0.3024,  0.0681, -0.0000, -0.3815,  2.8269]],
       grad_fn=<MulBackward0>)
tensor([[-0.5190, -0.1981,  0.5826, -0.0238, -0.1580,  0.8844, -0.9854],
        [-0.4224,  0.7566,  0.8419,  0.4887, -0.0442, -0.1842, -1.4694],
        [ 1.0135, -1.7524, -0.2117,  0.0477, -0.2945, -0.2670,  1.9788]],
       grad_fn=<AddmmBackward0>)


In [ ]:
layer = nn.Conv2d(in_channels = 1, out_channels = 2, kernel_size = 3) # stride=1, padding=0 이 디폴트 
layer(torch.randn(32, 1, 5, 5)).shape

torch.Size([32, 2, 3, 3])

In [ ]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # 채채 # 근데 얘는 채 또는 개채를 원함, 개x3 => 개x5
# nn.Conv2d(3,5) # 채채 # 근데 얘는 채행열 또는 개채행열을 원함, 개x3x행x열 => 개x5x행x열

torch.Size([32, 2, 3, 3])

In [ ]:
layer = nn.Conv2d(3, 5, 3) # weight (=필터=커널)가 3x3x3짜리 5개 존재(5x3x3x3)
print(layer(torch.randn(35, 3, 5, 5)).shape)
print(layer.weight.shape)

torch.Size([35, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [ ]:
conv1 = nn.Conv2d(1,8,6, stride = 2)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)
# 8x1x6x6 (8개의 특징으로 뽑아냄)

conv2 = nn.Conv2d(8,16,3, padding = 1) # 위에서 8개를 뽑아냈으므로 8개의 채널을 가진 걸16개로 뽑아냄냄
print(conv2(conv1(x)).shape)

#maxpooling (Maxpool 2로만 줘도 자동으로 kernel_size = 2, stride = 2)
Maxpool = nn.MaxPool2d(kernel_size = 2, stride = (2,2))
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [ ]:
maxpool = nn.MaxPool2d(2)
x = torch.randn(1,6,6)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[-1.2671, -1.3674, -0.2031, -2.5054, -1.2952, -1.1666],
         [-0.3636,  1.9674, -1.0052, -0.4916,  2.1518,  0.1958],
         [-1.8074,  1.2249,  1.5804, -1.5067,  0.8464,  0.3205],
         [-0.1269,  0.2478,  0.2744, -0.2630,  0.4021, -1.2519],
         [ 2.1584, -1.0529, -1.9150, -1.4069,  0.1849,  0.3869],
         [ 0.3588,  1.2618, -0.4371, -0.7771,  2.0771, -1.9846]]])
tensor([[[ 1.9674, -0.2031,  2.1518],
         [ 1.2249,  1.5804,  0.8464],
         [ 2.1584, -0.4371,  2.0771]]])
torch.Size([32, 3, 3, 3])


In [ ]:
maxpool = nn.AvgPool2d(2)
x = torch.randn(1,6,6)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[-1.6973,  0.4176,  1.2805, -0.6963,  0.7266, -0.2412],
         [ 0.8258, -0.5234, -0.3560, -1.5052,  0.8879, -1.1183],
         [-0.8007,  0.5926, -0.8668,  0.6090, -0.8903, -0.4078],
         [ 0.6985,  2.1096,  1.0604,  0.3729, -0.6818, -1.2578],
         [ 0.4783,  0.2312, -1.7342, -0.1264, -0.9615,  2.0580],
         [ 0.6023,  0.0623, -0.4100, -1.9286,  2.1107, -0.2622]]])
tensor([[[-0.2444, -0.3193,  0.0638],
         [ 0.6500,  0.2939, -0.8094],
         [ 0.3435, -1.0498,  0.7362]]])
torch.Size([32, 3, 3, 3])


In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6, 10)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool(x)
        x = torch.flatten(x, start_dim = 1)
        x = self.fc(x)
        return x

In [ ]:
model = CNN()
model

CNN(
  (conv1): Conv2d(1, 8, kernel_size=(6, 6), stride=(2, 2))
  (conv2): Conv2d(8, 16, kernel_size=(6, 6), stride=(1, 1), padding=(1, 1))
  (Maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc): Linear(in_features=18432, out_features=10, bias=True)
)

In [ ]:
x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 10])


## .parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x
        
model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [ ]:
model.parameters()

<generator object Module.parameters at 0x7f046f1886d0>

In [ ]:
list(model.parameters())[0]
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[-0.5683, -0.6002],
        [-0.5185, -0.1924],
        [ 0.0231, -0.1096]], requires_grad=True)

In [ ]:
# for transfer learning (전이학습)
model = MLP()
# 학습완료

for p in model.parameters(): # 전체 freeze
    p.requires_grad = False # backward시 전체에 대해 미분이 일어나지않음

model.fc_out = nn.Linear(4,10) # 10개 분류로 변경 (다시 requires_grad가 true로 변경됨)

# 마지막 requires_grad확인인
params = [p for p in model.parameters()]
print(params)
#backward()

from torch import optim
optimizer = optim.Adam(params, lr = 0.1)

[Parameter containing:
tensor([[-0.5330, -0.3082],
        [ 0.6608, -0.0414],
        [-0.4278,  0.4770]]), Parameter containing:
tensor([-0.6077, -0.1673, -0.2564]), Parameter containing:
tensor([[ 0.2484,  0.3453, -0.2130],
        [ 0.2475, -0.4583,  0.0360],
        [-0.2401, -0.3378, -0.0813],
        [ 0.0721,  0.0815,  0.2351]]), Parameter containing:
tensor([ 0.3105, -0.5657,  0.1300, -0.0681]), Parameter containing:
tensor([[ 0.0126, -0.3676,  0.2845, -0.3071],
        [ 0.0554,  0.2092, -0.3572,  0.3910],
        [ 0.3382, -0.1689,  0.2389,  0.3243],
        [ 0.4720,  0.4015, -0.0828,  0.4303],
        [ 0.0355, -0.2853, -0.1568,  0.1021],
        [ 0.0122,  0.2480, -0.0062, -0.2764],
        [ 0.1938, -0.3965,  0.2165,  0.1305],
        [ 0.3666, -0.3306,  0.0852,  0.0481],
        [-0.1427, -0.0468,  0.0161,  0.4874],
        [-0.1750,  0.0630, -0.0792, -0.3998]], requires_grad=True), Parameter containing:
tensor([-0.3234,  0.3842,  0.2709,  0.4646,  0.1472,  0.2518, -0.0

In [ ]:
list(model.named_parameters())
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]⎮

[('fc1.0.weight', Parameter containing:
  tensor([[-0.5330, -0.3082],
          [ 0.6608, -0.0414],
          [-0.4278,  0.4770]])), ('fc1.0.bias', Parameter containing:
  tensor([-0.6077, -0.1673, -0.2564])), ('fc2.0.weight', Parameter containing:
  tensor([[ 0.2484,  0.3453, -0.2130],
          [ 0.2475, -0.4583,  0.0360],
          [-0.2401, -0.3378, -0.0813],
          [ 0.0721,  0.0815,  0.2351]])), ('fc2.0.bias', Parameter containing:
  tensor([ 0.3105, -0.5657,  0.1300, -0.0681])), ('fc_out.weight',
  Parameter containing:
  tensor([[ 0.0126, -0.3676,  0.2845, -0.3071],
          [ 0.0554,  0.2092, -0.3572,  0.3910],
          [ 0.3382, -0.1689,  0.2389,  0.3243],
          [ 0.4720,  0.4015, -0.0828,  0.4303],
          [ 0.0355, -0.2853, -0.1568,  0.1021],
          [ 0.0122,  0.2480, -0.0062, -0.2764],
          [ 0.1938, -0.3965,  0.2165,  0.1305],
          [ 0.3666, -0.3306,  0.0852,  0.0481],
          [-0.1427, -0.0468,  0.0161,  0.4874],
          [-0.1750,  0.0630, -0.

In [ ]:
# 사용법
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[-0.5330, -0.3082],
        [ 0.6608, -0.0414],
        [-0.4278,  0.4770]])
fc1.0.bias
Parameter containing:
tensor([-0.6077, -0.1673, -0.2564])
fc2.0.weight
Parameter containing:
tensor([[ 0.2484,  0.3453, -0.2130],
        [ 0.2475, -0.4583,  0.0360],
        [-0.2401, -0.3378, -0.0813],
        [ 0.0721,  0.0815,  0.2351]])
fc2.0.bias
Parameter containing:
tensor([ 0.3105, -0.5657,  0.1300, -0.0681])
fc_out.weight
Parameter containing:
tensor([[ 0.0126, -0.3676,  0.2845, -0.3071],
        [ 0.0554,  0.2092, -0.3572,  0.3910],
        [ 0.3382, -0.1689,  0.2389,  0.3243],
        [ 0.4720,  0.4015, -0.0828,  0.4303],
        [ 0.0355, -0.2853, -0.1568,  0.1021],
        [ 0.0122,  0.2480, -0.0062, -0.2764],
        [ 0.1938, -0.3965,  0.2165,  0.1305],
        [ 0.3666, -0.3306,  0.0852,  0.0481],
        [-0.1427, -0.0468,  0.0161,  0.4874],
        [-0.1750,  0.0630, -0.0792, -0.3998]], requires_grad=True)
fc_out.bias
Parameter containing

In [ ]:
list(model.modules())
# 0은 전체, 1은 처음 fc1전체, 2는 fc1의 linear부분 ...

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ), Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Linear(in_features=2, out_features=3, bias=True), ReLU(), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=3, out_features=4, bias=True), ReLU(), Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
# 사용법
print([m for m in model.modules() if isinstance(m, nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m, nn.Linear)])
# nn.Linear에 대한 

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[-0.5330, -0.3082],
        [ 0.6608, -0.0414],
        [-0.4278,  0.4770]]), Parameter containing:
tensor([[ 0.2484,  0.3453, -0.2130],
        [ 0.2475, -0.4583,  0.0360],
        [-0.2401, -0.3378, -0.0813],
        [ 0.0721,  0.0815,  0.2351]]), Parameter containing:
tensor([[ 0.0126, -0.3676,  0.2845, -0.3071],
        [ 0.0554,  0.2092, -0.3572,  0.3910],
        [ 0.3382, -0.1689,  0.2389,  0.3243],
        [ 0.4720,  0.4015, -0.0828,  0.4303],
        [ 0.0355, -0.2853, -0.1568,  0.1021],
        [ 0.0122,  0.2480, -0.0062, -0.2764],
        [ 0.1938, -0.3965,  0.2165,  0.1305],
        [ 0.3666, -0.3306,  0.0852,  0.0481],
        [-0.1427, -0.0468,  0.0161,  0.4874],
        [-0.1750,  0.0630, -0.0792, -0.3998]], requires_grad=True)]
[None, None, None]


In [ ]:
# weight initialization 에 활용
for m in model.modules():
    if isinstance(m, nn.Linear): # nn.linear에 해당되는 부분만 1로 변경경
        nn.init.kaiming_normal_(m.weight)
        nn.init.constant_(m.weight, 1)
print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]), Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)]


In [ ]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# childeren 사용법 
## subnetwork 만들때 좋음
sub_network = nn.Sequential(*list(model.children())[:2]) # 블럭단위로 줌
print(sub_network)
sub_network(x)

Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)


tensor([[0.3105, 0.0000, 0.1300, 0.0000],
        [0.3105, 0.0000, 0.1300, 0.0000]])

## Sequential vs ModuleList

In [ ]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error! (for문으로 하나씩 돌려줘야함)
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
tensor([[ 1.2796e-04, -3.0337e-01, -3.8524e-02]], grad_fn=<AddmmBackward0>)
tensor([[ 1.2796e-04, -3.0337e-01, -3.8524e-02]], grad_fn=<AddmmBackward0>)


In [ ]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)] # 해당 모듈은 등록이 안되어있다.
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

tensor([[0.1428, 0.6363, 0.1973]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=3, bias=True)
  )
)


In [ ]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y): # 1. 입력받는 값 인자 2개
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block) # small블록을 2개를 만들어서 연결
print(model)
# model(torch.randn(1),torch.randn(1)) # error!
# 2. nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block]) # 그냥 리스트로 넣으면 등록이 안되기 때문에 modulelist를 이용
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)